language: objective-c
xcode_sdk: iphonesimulator
rvm: 1.9.3

before_install:
  - cd TestProject
  - gem install --no-rdoc --no-ri cocoapods -v 0.33

script:
  - xctool test -workspace TestProject.xcworkspace -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
